apiVersion: apps/v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox1
  labels:
    app: techtrends
spec:
  selector:
    matchLabels:
      app: techtrends
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  type: ClusterIP
